---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: nginx-ingress-controller
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.7.1
    chart: nginx-ingress-controller
    helm:
      values: |
        controller:
          ingressClassResource:
            default: true
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
        config:
          use-forwarded-headers: 'true'
          force-ssl-redirect: 'true'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
