---
apiVersion: v1
kind: Namespace
metadata:
  name: promotion-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordjs
  namespace: promotion-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discordjs
  template:
    metadata:
      labels:
        app: discordjs
    spec:
      containers:
      - name: discordjs
        image: ghcr.io/coinmoles/promotion-bot:2024-02-09_3
        envFrom:
        - secretRef:
            name: env
