apiVersion: v1
kind: Secret
metadata:
  name: env
  namespace: promotion-bot
type: Opaque
stringData:
  TOKEN: "discord bot token here"
  CLIENT_ID: "discord bot client id here"
  GUILD_ID: "upnl discord guild id here"
  PROJECT_ID: "firebase project id here"
  PRIVATE_KEY: "firebase private key here"
  CLIENT_EMAIL: "firebase client email here"